### ISSUE TITLE
OAuth 2 MUST utilize https

### ISSUE THREAD

**Issue by celeriev** [data-platform-hq/mlflow-oidc-auth#42]
Again, thanks a lot for the plugin. When using it I faced: https://github.com/requests/requests-oauthlib/issues/287 

I managed to solve it by adding 
```
    https_authorization_url = request.url.replace('http://', 'https://')
    # Get the access token from the authorization code
    token_url, headers, body = auth_client.prepare_token_request(
        AppConfig.get_property("OIDC_TOKEN_URL"),
        authorization_response=https_authorization_url,
        redirect_url=AppConfig.get_property("OIDC_REDIRECT_URI"),
        code=_get_request_param("code"),
        client_secret=AppConfig.get_property("OIDC_CLIENT_SECRET"),
    )
```

Is it fine for me to open a PR to solve this?

**Comment by kharkevich** [comment]
It appears that your deployed application is using plain HTTP instead of HTTPS. You have two options to address this:
- add SSL/TLS to the MLflow Tracking server by using an external reverse proxy, such as apache2, nginx, ambassador, envoy, etc.
- disable the strict HTTPS requirement for the oauth library by setting the environment variable `OAUTHLIB_INSECURE_TRANSPORT`

more details you can find here: https://oauthlib.readthedocs.io/en/latest/oauth2/security.html?highlight=oauthlib_insecure_transport

**Comment by celeriev** [comment]
Thanks @kharkevich, I work with cloufdlare, which provides SSL termination. This is why I did not invest in a reverse nginx proxy. 
In that case, I will use the OAUTHLIB_INSECURE_TRANSPORT variable indeed. thanks
